backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'cases'
    label: 'Cases'
    folder: 'content/cases'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Data de Publicação', name: 'date', widget: 'datetime' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - { label: 'Corpo', name: 'body', widget: 'markdown' }
      - { label: 'Prévia', name: 'thumbnail', widget: 'image' }
      - { label: 'Imagem Destaque', name: 'feature_img', widget: 'image' }
  - name: 'home'
    label: 'Página Inicial'
    files:
      - label: 'Abas de Conteúdo'
        name: content_tabs
        file: 'content/copy/content_tabs.yml'
        fields:
          - { label: 'Título', name: 'title', widget: 'string' }
          - label: "Aba 1"
            name: "tab1"
            widget: "object"
            fields:
              - {label: 'Título', name: 'title', widget: 'string'} 
              - {label: 'Texto', name: 'text', widget: 'string'}
              - {label: 'Imagem', name: 'img', widget: 'image'}
          - label: "Aba 2"
            name: "tab2"
            widget: "object"
            fields:
              - {label: 'Título', name: 'title', widget: 'string'} 
              - {label: 'Texto', name: 'text', widget: 'string'}
              - {label: 'Imagem', name: 'img', widget: 'image'}
          - label: "Aba 3"
            name: "tab3"
            widget: "object"
            fields:
              - {label: 'Título', name: 'title', widget: 'string'} 
              - {label: 'Texto', name: 'text', widget: 'string'}
              - {label: 'Imagem', name: 'img', widget: 'image'}
          - label: "Aba 4"
            name: "tab4"
            widget: "object"
            fields:
              - {label: 'Título', name: 'title', widget: 'string'} 
              - {label: 'Texto', name: 'text', widget: 'string'}
              - {label: 'Imagem', name: 'img', widget: 'image'}
          - label: "Aba 5"
            name: "tab5"
            widget: "object"
            fields:
              - {label: 'Título', name: 'title', widget: 'string'} 
              - {label: 'Texto', name: 'text', widget: 'string'}
              - {label: 'Imagem', name: 'img', widget: 'image'}
          - label: "Aba 6"
            name: "tab6"
            widget: "object"
            fields:
              - {label: 'Título', name: 'title', widget: 'string'} 
              - {label: 'Texto', name: 'text', widget: 'string'}
              - {label: 'Imagem', name: 'img', widget: 'image'}
          - label: "Aba 7"
            name: "tab7"
            widget: "object"
            fields:
              - {label: 'Título', name: 'title', widget: 'string'} 
              - {label: 'Texto', name: 'text', widget: 'string'}
              - {label: 'Imagem', name: 'img', widget: 'image'}
          - label: "Aba 8"
            name: "tab8"
            widget: "object"
            fields:
              - {label: 'Título', name: 'title', widget: 'string'} 
              - {label: 'Texto', name: 'text', widget: 'string'}
              - {label: 'Imagem', name: 'img', widget: 'image'}
